[package]
name = "yukako"
version = "0.1.0"
edition = "2024"

[dependencies]
capnp = "0.21"
typed-builder = "0.21.0"

[build-dependencies]
capnpc = "0.21"
pkg-config = "0.3.32"
reqwest = { version = "0.12.15", features = ["blocking"] }
